### ISSUE TITLE
Rotation Matrix error uncaught for unavaible SPICE kernels

### ISSUE THREAD

**Issue by addy999** [open-space-collective/open-space-toolkit-physics#21]
For an unavailable time period from the SPICE kernels, an unexpected `{First Column} is undefined` error is thrown instead of a polar motion error - which occurs for a time much later in the future.

Error is raised from [LibraryMathematics ](https://github.com/open-space-collective/library-mathematics/blob/54d27d5a5b89bd8b36231b2963b54360b8aebeb1/src/Library/Mathematics/Geometry/3D/Transformations/Rotations/RotationMatrix.cpp#L450)

![image](https://user-images.githubusercontent.com/15189112/55521281-fe861900-5634-11e9-9f21-4682f0386ef8.png)

**Comment by kyle-cochran** [comment]
I know this is an old issue, but I ran into the same thing recently and tracked it down to an error in the `Finals2000A` data file handling. [Fix in this MR.](https://github.com/open-space-collective/open-space-toolkit-physics/pull/162/files)

Propagating into the future tries to fetch the `polar motion` in order to do the frame conversion to ITRF. The `{First column} is undefined` error comes from [this line](https://github.com/open-space-collective/open-space-toolkit-physics/blob/main/src/OpenSpaceToolkit/Physics/Coordinate/Frame/Providers/ITRF.cpp#L104).

It's due to the polar motion computed a few lines above being a `nan`. Seems that the valid data range that we define for the Finals2000A data class is a bit larger than the actual range over which it's able to provide valid polar motion predictions. Added a check to see when the return from that function is invalid, and give a more useful error message.

Looks like at the moment, we're only able to propagate about 1 year into the future (at least when ITRF/TEME frame conversions are required). 

Gonna close this one out!
